title: BLEDiff
description: An automated, scalable,property-agnostic, and black-box protocol noncompliance checking framework for Bluetooth Low Energy (BLE) devices
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
show_downloads: false
theme: jekyll-theme-cayman
github:
  owner_url: https://github.com/BLEDiff
  owner_name: BLEDiff
  repository_url: https://github.com/BLEDiff/BLEDiff
  is_project_page: true
